#!/usr/bin/env bash
# Installs Nginx in an Ubuntu machine with these requirements:
#	+ listen on port 80
# 	+ When querying Nginx at its root / with a GET request (requesting a page) using curl,
# it must return a page that contains the string 'Hello World!'

apt-get update
apt-get -y install nginx
ufw allow "Nginx HTTP"
ufw enable
chmod 666 /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
