#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes.
hour=0
min=60
while [[ $hour -ne 12 || $min -ne 60 ]]
do
	if ((min == 60))
	then
		echo "Hour: $hour"
		((hour++))
		((min=1))
	else
		echo "$min"
		((min++))
	fi
done
