#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while
fname=school
if [ ! -e "$fname" ]
then
	echo "$fname file does not exist"
else
	echo "$fname file exists"
	if [ ! -s "$fname" ]
	then
		echo "$fname file is empty"
	else
		echo "$fname file is not empty"
	fi
	if [ -f "$fname" ]
	then
		echo "$fname is a regular file"
	fi
fi
