#!/usr/bin/env bash
# Configures an Ubuntu server with these requirements:
# localhost -> to 127.0.0.2 and facebook.com -> to 8.8.8.8
cp /etc/hosts hosts.new
# cat hosts.new
sed -i s/127.0.0.1/127.0.0.2/ hosts.new
echo -e "\n8.8.8.8 \t facebook.com" >> hosts.new
cat hosts.new
#cp -f hosts.new /etc/hosts
